### ISSUE TITLE
ResourceBundle documentation link broken

### ISSUE THREAD

**Issue by iBasit** [symfony-cmf/resource#22]
broken link for ResourceBundle documentation

Need to see how I can get this or rest bundle working, because I'm getting _cmf_resource not found error

**Comment by dantleech** [comment]
@iBasit there is no documentation for this bundle as its still in development. Can you provide a stack trace? Sounds like you are perhaps not importing the routing file from ResourceRestBundle .. maybe?

**Comment by iBasit** [comment]
Ya that most likely it, but there is nothing mention about it. Can you please provide import link or path, I can try to import that as well. 

```

cmf_create_rest:
    resource: "@CmfCreateBundle/Resources/config/routing/rest.xml"

#cmf_create_image:
#    resource: "@CmfCreateBundle/Resources/config/routing/image.xml"

cmf_tree:
    resource: .
    type: 'cmf_tree'

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

```
